name: Run tests
on: [push]

env: 
  SHOULD_RUN_COVERAGE: ${{ !(github.event.push.branches == 'master' || github.event.issue.pull_request) }}

jobs:
  coverage: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run Tests
      if: ${{ !env.SHOULD_RUN_COVERAGE }}
      run: npm test
    - name: Calc Coverage
      if: ${{ env.SHOULD_RUN_COVERAGE }}
      run:  npm run test-coverage
    - name: Coveralls
      if: ${{ env.SHOULD_RUN_COVERAGE }}
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
