name: test coverage
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  coverage: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - name: Calc Coverage
      run:  npm run test-coverage
    - name: Coveralls
      uses: coveralls/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
